---
- name: Install kubernetes (RedHat)
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  block:
    - name: add kubernetes rpm repository
      template:
        src: templates/kubernetes.repo.j2
        dest: "/etc/yum.repos.d/kubernetes.repo"
        owner: "root"
        mode: 0644

    - name: install kubernetes (rpm distro)
      dnf:
        disable_excludes: kubernetes
        update_cache: yes
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

- name: Install kubernetes (Debian)
  become: true
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: get kubernetes apt key
      get_url:
        url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

    - name: add kubernetes apt repo
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /"
        filename: "kubernetes"
        state: present

    - name: install kubernetes (deb distro)
      apt:
        update_cache: yes
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: prevent kube package from being upgraded (deb distro)
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - kubeadm
        - kubectl
        - kubelet

- name: Enable and start kubelet service
  become: true
  systemd:
    state: started
    daemon_reload: yes
    name: kubelet
    enabled: yes
