---
- name: Prep OS
  import_tasks: prep_os.yml

- name: Install and configure containerd
  import_tasks: containerd.yml

- name: Install Kubernetes components
  import_tasks: kube_components.yml

- name: Initialize control plane
  import_tasks: init_cp.yml
  when: inventory_hostname == groups["k8s_cp"][0]
