---
- name: Prep OS
  import_tasks: prep_os.yml

- name: Install and configure containerd
  import_tasks: containerd.yml

- name: Install Kubernetes components
  import_tasks: kube_components.yml

- name: Initialize control plane
  import_tasks: init_cp.yml
  when: inventory_hostname == groups["k8s_cp"][0]

- name: Configure user to use kubectl command
  import_tasks: configure_user.yml
  when: inventory_hostname == groups["k8s_cp"][0]

- name: Setup CNI
  import_tasks: pod_network.yml
  when: inventory_hostname == groups["k8s_cp"][0]

- name: Join nodes
  import_tasks: join_nodes.yml
  when: inventory_hostname == groups["kube_node"][0]
