---
- name: Check if Calico deployment exists
  command: "kubectl get deployments -n kube-system calico-kube-controllers"
  register: is_calico_controller_exists
  ignore_errors: true
  changed_when: false

- when: is_calico_controller_exists.rc != 0
  block:
    - name: Download calico manifest for the specified version
      get_url:
        url: "{{ calico_url }}"
        dest: ~/calico-manifest.yaml
        mode: "0440"

    - name: Apply Calico pod network
      command: "kubectl apply -f ~/calico-manifest.yaml"
