---
# Need to be adapted
- name: Verify backup dir
  ansible.builtin.stat:
    path: "{{ backup_dir_path }}"
  register: backup_dir_stat

- name: Print a debug message
  ansible.builtin.debug:
    msg: "Backup dir not found"
  when: not backup_dir_stat.stat.exists

- block:
    - name: Stop pod before backup
      ansible.builtin.systemd:
        name: "{{ service_or_pod }}.service"
        state: stopped
        scope: user

    - name: Backup Podman Volume
      containers.podman.podman_export:
        volume: "{{ volume_to_backup }}"
        dest: "{{ backup_dir_path }}/{{ volume_to_backup }}.tar"

    - name: Start pod after backup
      ansible.builtin.systemd:
        name: "{{ service_or_pod }}.service"
        state: started
        scope: user
  when: backup_dir_stat.stat.exists
