---
- name: Ensure podman is installed.
  become: true
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure lingering is enable for user.
  become: true
  command:
    cmd: "loginctl enable-linger {{ ansible_user }}"
    ##{{ item.name }}"
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"
##  with_items:
##    - "{{ ansible_user }}"

- name: Enable podman restart service for user.
  # When not use with systemd to manage containers
  when: enable_podman_restart_service
  systemd:
    state: started
    name: podman-restart.service
    enabled: true
    scope: user

- name: Enable podman socket for user.
  when: enable_podman_socket
  systemd:
    state: started
    name: podman.socket
    enabled: true
    scope: user
