---
- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io/
    timeout: 120
    dest: /tmp/k3s-install.sh
    mode: "0755"

- name: Execute K3s install script
  become: true
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh
    creates: "/etc/rancher/k3s/k3s.yaml"
  #environment:
  #  INSTALL_K3S_SKIP_START: "true"
  #  INSTALL_K3S_VERSION: "{{ k3s_version }}"
