---
- name: Enable automatic updates (RedHat)
  when: ansible_facts['os_family'] == "RedHat"
  block:
    - name: Install dnf-automatic package
      become: true
      ansible.builtin.package:
        name: dnf-automatic
        state: present

    - name: Set automatic.conf file
      copy:
        src: "files/automatic.conf"
        dest: "/etc/dnf/automatic.conf"
        owner: "root"
        group: "root"
        mode: 0644

    - name: Enable dnf automatic timer
      ansible.builtin.systemd_service:
        name: dnf-automatic.timer
        scope: system
        state: started
        enabled: true
        daemon_reload: true

- name: Enable automatic updates (Debian)
  when: ansible_facts['os_family'] == "Debian"
  become: true
  notify: restart unattended
  block:
    - name: Install unattended-upgrades package
      ansible.builtin.package:
        name: unattended-upgrades
        state: present

    - name: Set config file to enable reboot
      copy:
        src: "files/52unattended-upgrades-local"
        dest: "/etc/apt/apt.conf.d/52unattended-upgrades-local"
        owner: "root"
        group: "root"
        mode: 0644
