---
- name: Install packages
  import_tasks: install_packages.yml

- name: Update all packages and reboot
  import_tasks: update_all_packages.yml
  when: update_all_packages

- name: Disable Firewall
  import_tasks: disable_firewall.yml
  when: disable_firewall

- name: Mount drives
  import_tasks: mount_drives.yml
  when: drives_to_mount | length > 0
