---
- name: Verify backup dir
  ansible.builtin.stat:
    path: "/data/containers"
  register: backup_dir_stat

- name: Print a debug message
  ansible.builtin.debug:
    msg: "Backup dir not found"
  when: not backup_dir_stat.stat.exists

- block:
    - name: Stop jellyfin before backup
      ansible.builtin.systemd:
        name: "{{ jellyfin_service }}.service"
        state: stopped
        scope: user

    - name: Backup Podman Volume
      containers.podman.podman_export:
        volume: "{{ jellyfin_volume }}"
        dest: "/data/containers/{{ jellyfin_volume }}.tar"

    - name: Start jellyfin after backup
      ansible.builtin.systemd:
        name: "{{ jellyfin_service }}.service"
        state: started
        scope: user
  when: backup_dir_stat.stat.exists
