---
- name: Get service facts
  ansible.builtin.service_facts:
  become: true

- name: Manage {{ container_config.name }} container firewalld port
  ansible.posix.firewalld:
    port: "{{ container_config.firewall_port }}"
    permanent: true
    state: enabled
    immediate: true
    #zone:
  become: true
  when:
    - "'firewalld.service' in ansible_facts.services"
    - ansible_facts.services['firewalld.service']['status'] == 'enabled'
    - container_firewall_port != ""
