---
- name: Get service facts
  ansible.builtin.service_facts:
  become: true

- name: Manage {{ container_name }} container firewalld port
  ansible.posix.firewalld:
    port: "{{ container_port_on_host }}/tcp"
    permanent: true
    state: enabled
    immediate: true
    #zone:
  become: true
  when:
    - ansible_facts.services.get('firewalld.service', {}) | length
    - ansible_facts.services['firewalld.service']['status'] == 'enabled'
