---
- name: Ensure {{ container_config.name }} container is running
  ansible.builtin.systemd:
    name: "{{ container_config.name }}.service"
    state: started
    enabled: true
    scope: user
    daemon_reload: true
