---
- name: Ensure {{ container_name }} container is running
  ansible.builtin.systemd:
    name: "container-{{ container_name }}.service"
    state: started
    enabled: true
    scope: user
    daemon_reload: true
