---
- name: Enable automatic updates
  hosts: all
  vars:
    packages_to_install:
      - curl
      - rsync
      - vim
    enable_podman_restart_service: true
    enable_podman_socket: true
  roles:
    - role: common
    - role: automatic_updates
    - role: podman

- name: Setup storage
  hosts: worker1
  tasks:
    - name: Ensure drive is mounted
      become: true
      ansible.posix.mount:
        path: "{{ worker1_drive_mountpoint }}"
        src: LABEL={{ worker1_drive_label }}
        fstype: "{{ worker1_drive_fstype }}"
        state: mounted
