---
- name: Prep OS
  hosts: all
  vars:
    packages_to_install:
      - curl
      - rsync
      - vim
    enable_podman_restart_service: true
    enable_podman_socket: true
  roles:
    - role: common
    - role: automatic_updates
    - role: podman
