---
- name: Enable automatic updates for RedHat
  import_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable automatic updates for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
