---
- become: true
  block:
    - name: Install dnf-automatic package
      ansible.builtin.package:
        name: dnf-automatic
        state: present

    - name: Set automatic.conf file
      copy:
        src: "files/automatic.conf"
        dest: "/etc/dnf/automatic.conf"
        owner: "root"
        group: "root"
        mode: 0644

    - name: Enable dnf automatic timer
      ansible.builtin.systemd_service:
        name: dnf-automatic.timer
        scope: system
        state: started
        enabled: true
        daemon_reload: true
